minor

diff --git a/make/Makefile_defs b/make/Makefile_defs
--- a/make/Makefile_defs
+++ b/make/Makefile_defs
@@ -244,8 +244,8 @@ endif
 # Note: GNU make version 3.81 cannot have an " =" at the end of the next line; strange.
 # Also, generally it appears unsafe to embed comments within a define..endef definition.
 define cmd_hcheck
-  @hcheck $< >/dev/null
-  @if [ ! -e $(@:%.ou=%.diff) ]; then \
+  @hcheck $< >/devnull; status=$$?; if [[ $$status -ne 0 ]]; then echo "$@:1:1: error: hcheck $< exit $$status"; fi; \
+  if [ ! -e $(@:%.ou=%.diff) ]; then \
     echo "$@"; \
   else \
     echo "$@:1:1: error: test output differs:  ediff $(@:%.ou=%).{ref,ou}"; \
@@ -254,7 +254,8 @@ define cmd_hcheck
     elif [[ -e $@ ]] && [[ `cat $@ | wc -l` -le 30 ]]; then \
       cat $@; \
     fi; \
-  fi;
+  fi; \
+  # exit $$status
 endef
 
 # Test the program % by saving its output into %.ou and then comparing it with the reference output in %.ref
